# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Identify My iPad
facebook: identifymyipad
email: identifymyipad@davidalbertoadler.com
description: >
  Identify Your iPad. Buy the top rated compatible iPad cases and accessories.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://identifymyipad.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
author: David Alberto Adler
twitter:
  username: da_adler
  card: summary
logo: /assets/images/logo.png
lang: en_GB
markdown: kramdown
